export type Player = {
  TeamID: number | null;
  SEASON: string | null;
  LeagueID: string | null;
  PLAYER: string;
  NICKNAME: string | null;
  PLAYER_SLUG: string | null;
  NUM: string | null;
  POSITION: string;
  HEIGHT: string | null;
  WEIGHT: string | null;
  BIRTH_DATE: string | null;
  AGE: number | null;
  EXP: string | null;
  SCHOOL: string | null;
  PLAYER_ID: number;
  HOW_ACQUIRED: string | null;
  NAME?: string | null;
  LAST_NAME?: string | null;
};
